name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am Pakistan Standard Time
    - cron: '00 19 * * *'

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: windows-2019
    steps:
      - uses: anmol098/waka-readme-stats@V3
        with:
          GH_TOKEN:  ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY:  ${{ secrets.WAKATIME_API_KEY }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
